version: "3"
services:
  mpsse-dev:
    container_name: mpsse-dev
    image: vaporio/mpsse-dev
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/mpsse
    command: bin/sleep.sh
